Add custom exception
packagist/vendor-data-exporter pull request #3
Opened 2024-05-26 19:05 UTC by Chemaclass

A little refactoring adding a custom exception `MissingApiCredentialsException `

2024-05-27 12:23 UTC, pscheit reviewed
Hey!

thanks for the PR! I was wondering two things

1. were the unrelated code style changes introduced cause you ran the php cs fixer? Our codestyle imho doesnt require to break long lines.
2. Why do we need a Custom Exception in the console command?

2024-05-28 11:25 UTC, Chemaclass commented
Hi, @pscheit ! thanks for the feedback. Regarding those questions:
1.  Well, that's kind of a mix. But mostly, I thought it would be way easier to read the line if we break the long lines into multiline; at least for readability purposes.
2. The custom exception is to simplify the readability by using a named constructor for it, so the message of the exception is a hidden in the detail. It might not be required or adding huge value/impact, but I thought it would be worth showing it as an example to see your thoughts too :)

2024-05-28 11:28 UTC, Chemaclass commented
I was thinking, as next step, I would like to try to refactor it to get rid of the testing public method
```php
    /** @test */
    public function setPackagistApiClient(PackagistApiClient $client): void
    {
        $this->packagistApiClient = $client;
    }
```
and, for example, consider injecting this via the constructor, instead of using a public setter specificaly for the test. This way, we can inject and mock the interface in the test, while using the real instanciation on the prod code - moving the logic from `getPackagistApiClient()` up to `bin/console`, for example.

2024-05-29 07:34 UTC, pscheit requested changes
I still dont see much value in adding those exception, but they don't hurt either :)

So happy to merge if the you revert the unrelated changes

2024-05-29 07:34 UTC, pscheit commented on src/Command/ListCommand.php
Can you revert those multi lines to be just single line as before? Thanks

2024-05-29 07:36 UTC, pscheit commented
I mean sure, if you want to, go for it.

2024-05-29 09:53 UTC, Chemaclass commented
Good for me. Do you mean the option and/or the array_map usage? I would personally prefer to keep the array_map calls in multiline (as they read it simpler). Would that be ok, or would you prefer to rollback both of them and move this to a different PR to unblock the other changes?

2024-05-29 15:22 UTC, pscheit commented
Please, just provide the changes with the custom exception and the phpunit changes.
Remove all other style changes.

I wouldn't suggest working on this repo further and sending more PRs. This is really just a small demo which might not be the nicest code but really is enough to demonstrate.

Thanks for your efforts!

2024-05-30 11:42 UTC, Chemaclass commented
@pscheit can you check it again? thanks!

2024-05-30 13:28 UTC, pscheit approved these changes
thanks

2024-05-30 13:29 UTC, merged